export const STRATEGIES = Object.freeze({
  conservative: {
    label: 'Conservative strategy',
    risk: 'Lower',
    yield: '3.2%',
    exit: 'High liquidity',
    network: 'Arbitrum',
    cost: '0.18%',
    policyBuffer: 0.18,
    reserve: '45%',
    cap: '30%',
    trigger: 'Utilization > 82%',
    mechanics: {
      borrowing: 'No',
      borrowedAsset: 'None',
      maxLtv: '0%',
      minHealth: 'Not applicable',
      maxLeverage: '1.00×',
      loops: '0',
      liquidation: 'No borrowing liquidation risk',
    },
    explanation:
      'Keep a large liquid reserve and use a limited set of lower-complexity lending routes.',
    decision:
      'Reserve remains elevated while lending utilization is above the illustrative comfort range.',
    base: [
      { id: 'reserve', label: 'Liquid reserve', percent: 50, color: '#8b5cf6' },
      { id: 'lending', label: 'Diversified lending', percent: 35, color: '#38bdf8' },
      { id: 'short', label: 'Short-duration routes', percent: 15, color: '#2dd4bf' },
    ],
    pro: [
      {
        id: 'reserve',
        label: 'Liquid reserve',
        percent: 50,
        apy: '0.0%',
        color: '#8b5cf6',
        position: 'ARB-USDC-RES',
        proof: 'Recorded',
        operation: 'Held liquid',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'aave',
        label: 'Aave V3',
        percent: 25,
        apy: '6.8%',
        color: '#60a5fa',
        position: 'ARB-AAVE-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'morpho',
        label: 'Morpho',
        percent: 15,
        apy: '7.2%',
        color: '#67e8f9',
        position: 'ARB-MOR-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'euler',
        label: 'Euler V2',
        percent: 10,
        apy: '7.8%',
        color: '#2dd4bf',
        position: 'ARB-EUL-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
    ],
  },
  balanced: {
    label: 'Balanced strategy',
    risk: 'Moderate',
    yield: '5.1%',
    exit: 'Balanced',
    network: 'Arbitrum',
    cost: '0.34%',
    policyBuffer: 0.32,
    reserve: '20%',
    cap: '35%',
    trigger: 'Utilization > 78%',
    mechanics: {
      borrowing: 'No in this example',
      borrowedAsset: 'None',
      maxLtv: '0%',
      minHealth: 'Not applicable',
      maxLeverage: '1.00×',
      loops: '0',
      liquidation: 'No borrowing liquidation risk',
    },
    explanation:
      'Balance available liquidity with several diversified lending and liquidity routes.',
    decision: 'Keep a larger reserve while lending utilization remains elevated.',
    base: [
      { id: 'reserve', label: 'Liquid reserve', percent: 25, color: '#8b5cf6' },
      { id: 'lending', label: 'Diversified lending', percent: 45, color: '#38bdf8' },
      { id: 'liquidity', label: 'Additional lending markets', percent: 30, color: '#2dd4bf' },
    ],
    pro: [
      {
        id: 'reserve',
        label: 'Liquid reserve',
        percent: 25,
        apy: '0.0%',
        color: '#8b5cf6',
        position: 'ARB-USDC-RES',
        proof: 'Recorded',
        operation: 'Held liquid',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'aave',
        label: 'Aave V3',
        percent: 30,
        apy: '7.2%',
        color: '#60a5fa',
        position: 'ARB-AAVE-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'euler',
        label: 'Euler V2',
        percent: 25,
        apy: '8.4%',
        color: '#2dd4bf',
        position: 'ARB-EUL-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'morpho',
        label: 'Morpho',
        percent: 20,
        apy: '7.5%',
        color: '#67e8f9',
        position: 'ARB-MOR-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
    ],
  },
  opportunity: {
    label: 'Opportunity strategy',
    risk: 'Higher',
    yield: '7.8%',
    exit: 'Variable',
    network: 'Arbitrum',
    cost: '0.62%',
    policyBuffer: 0.355,
    reserve: '10%',
    cap: '40%',
    trigger: 'Risk score changes',
    mechanics: {
      borrowing: 'Yes, on approved loop routes',
      borrowedAsset: 'USDC',
      maxLtv: '62%',
      minHealth: '1.60',
      maxLeverage: '1.75×',
      loops: '2',
      liquidation: 'Present on collateralized routes',
    },
    explanation:
      'Accept more moving parts and variable liquidity in exchange for a wider eligible opportunity set.',
    decision:
      'Opportunity routes remain capped so no single position dominates the illustrative strategy.',
    base: [
      { id: 'reserve', label: 'Liquid reserve', percent: 10, color: '#8b5cf6' },
      { id: 'lending', label: 'Lending routes', percent: 40, color: '#38bdf8' },
      { id: 'opportunity', label: 'Opportunity routes', percent: 50, color: '#f59e0b' },
    ],
    pro: [
      {
        id: 'reserve',
        label: 'Liquid reserve',
        percent: 10,
        apy: '0.0%',
        color: '#8b5cf6',
        position: 'ARB-USDC-RES',
        proof: 'Recorded',
        operation: 'Held liquid',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'aave',
        label: 'Aave V3',
        percent: 25,
        apy: '8.5%',
        color: '#60a5fa',
        position: 'ARB-AAVE-SUP',
        proof: 'Linked',
        operation: 'Supply-only lending',
        supplied: 'USDC',
        borrowed: 'None',
        ltv: '0%',
        health: 'N/A',
        leverage: '1.00×',
        loop: 'None',
      },
      {
        id: 'euler',
        label: 'Euler V2 loop',
        percent: 30,
        apy: '11.2%',
        color: '#2dd4bf',
        position: 'ARB-EUL-LOOP',
        proof: 'Linked',
        operation: 'Collateralized lending loop',
        supplied: 'USDC',
        borrowed: 'USDC',
        ltv: '39.4%',
        health: '2.08',
        leverage: '1.65×',
        loop: '2 cycles',
        yieldMechanics:
          '(8.0% supply × 1.65 exposure) − (4.4% borrow × 0.65 debt) + 0.86% incentives = 11.20%',
      },
      {
        id: 'morpho',
        label: 'Morpho loop',
        percent: 35,
        apy: '9.4%',
        color: '#f59e0b',
        position: 'ARB-MOR-LOOP',
        proof: 'Linked',
        operation: 'Collateralized lending loop',
        supplied: 'USDC',
        borrowed: 'USDC',
        ltv: '31.0%',
        health: '2.65',
        leverage: '1.45×',
        loop: '1 cycle',
        yieldMechanics:
          '(8.0% supply × 1.45 exposure) − (4.5% borrow × 0.45 debt) − 0.175% route costs = 9.40%',
      },
    ],
  },
});

export const STRATEGY_DETAILS = Object.freeze({
  conservative: {
    purpose:
      'Prioritizes liquidity, simpler routes and a larger reserve before seeking additional yield.',
    tradeoff:
      'A more defensive allocation can produce a lower expected return and may leave more capital unallocated.',
    evidence:
      'Reserve level, approved routes, protocol shares, policy limits and every resulting transaction remain separately inspectable.',
  },
  balanced: {
    purpose:
      'Combines an available reserve with diversified routes to balance liquidity, return and operational complexity.',
    tradeoff:
      'More routes add dependencies. Utilization, withdrawal liquidity and concentration must be monitored continuously.',
    evidence:
      'Each route, share, illustrative APY, selection rationale and evidence package remains visible.',
  },
  opportunity: {
    purpose:
      'Uses a wider eligible route set and accepts more moving parts in pursuit of a higher expected result.',
    tradeoff:
      'Liquidity can be more variable and exposure to protocol, utilization and market conditions is greater.',
    evidence:
      'Route caps, risk triggers, allocation records and on-chain references make the additional complexity explicit.',
  },
});

export const ROUTE_DETAILS = Object.freeze({
  reserve: [
    'Keeps part of the deposit available instead of placing everything into an external protocol.',
    'It makes withdrawals easier, but money held in reserve normally earns little or no yield.',
  ],
  lending: [
    'Lending means depositing assets into approved markets that make liquidity available to borrowers. Borrowers pay interest; that interest produces the lending yield.',
    'The borrower interacts with the protocol, never with your wallet. Returns and withdrawals still depend on protocol liquidity and market utilization.',
  ],
  short: [
    'Uses simpler lending positions intended to remain easier to exit and to avoid long chains of dependent operations.',
    'Short-duration does not mean risk-free: the protocol can still have limited liquidity, changing utilization or technical failures.',
  ],
  liquidity: [
    'Adds more approved lending markets so the position does not depend on a single protocol or rate.',
    'Diversification reduces concentration, but each additional market introduces another protocol and liquidity dependency.',
  ],
  opportunity: [
    'Includes advanced routes that may borrow against supplied collateral and re-supply the borrowed asset to increase exposure.',
    'A loop can increase expected yield and risk together. Borrow cost, health factor, liquidation thresholds and exit liquidity become essential.',
  ],
  aave: [
    'Aave V3 is a decentralized lending market. In a supply-only route, the vault supplies USDC and receives the variable interest paid by borrowers without taking a loan.',
    'Its APY changes with utilization: when more supplied liquidity is borrowed, rates can rise, while available withdrawal liquidity can fall.',
  ],
  euler: [
    'Euler V2 provides modular lending vaults. Jethos can use a simple supply-only position or, only in an eligible Opportunity route, a collateralized borrow-and-resupply loop.',
    'The exact Euler market, collateral rules, borrow rate, utilization, health factor and adapter limits must all remain within policy.',
  ],
  morpho: [
    'Morpho exposes lending markets and managed vault routes. Jethos can supply assets directly or use a specifically approved collateralized loop in the Opportunity tier.',
    'Market capacity, oracle and collateral configuration, borrow cost, health factor and available liquidity require continuous checks.',
  ],
});

export type StrategyId = keyof typeof STRATEGIES;
export type Strategy = (typeof STRATEGIES)[StrategyId];
export type StrategyLevel = 'base' | 'pro' | 'advanced';

export const isStrategyId = (value: string | undefined): value is StrategyId =>
  Boolean(value && Object.hasOwn(STRATEGIES, value));

export const grossYield = (strategy: Strategy): number =>
  strategy.pro.reduce(
    (total, route) => total + (route.percent / 100) * Number.parseFloat(route.apy),
    0,
  );
